apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gaia
  labels:
    app: gaia
spec:
  selector:
    matchLabels:
      app: gaia
  endpoints:
  - port: metrics
    interval: 30s