apiVersion: v1
kind: Service
metadata:
  name: gaia
  labels:
    app: gaia
spec:
  ports:
  - port: 26656
    name: p2p
  - port: 26657
    name: rpc
  - port: 26660
    name: metrics
  selector:
    app: gaia